services:
  web:
    build: .
    container_name: laura_nails
    restart: unless-stopped
    environment:
      - SECRET_KEY=clave-super-secreta-para-laura-nails-2026
      - FLASK_ENV=production
      - SETUP_TOKEN=token-setup-laura-nails-2026
      - SEED_PASS_ADMIN=admin123
      - SEED_PASS_MANI1=manicurista1
      - SEED_PASS_MANI2=manicurista2
      - SEED_PASS_MANI3=manicurista3
      - IG_TOKEN=
      - DOCKER_CONTAINER=1
    ports:
      - "8001:8000"
    volumes:
      - ./instance:/app/instance